// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAChF4hZA6jWlfHLQwWSXqM2BXO1U7Zw2U',
    appId: '1:630175539288:web:7251ec1aaa00c71c5eaa2d',
    messagingSenderId: '630175539288',
    projectId: 'barakahtime-cbfa8',
    authDomain: 'barakahtime-cbfa8.firebaseapp.com',
    storageBucket: 'barakahtime-cbfa8.firebasestorage.app',
    measurementId: 'G-X198MTYC6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcE_VEirh5mnoR5WjdjNMDk0UVoiySuWU',
    appId: '1:630175539288:android:aa573dbd4b9ea45f5eaa2d',
    messagingSenderId: '630175539288',
    projectId: 'barakahtime-cbfa8',
    storageBucket: 'barakahtime-cbfa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByjfjoy8PV0iHj-L2-quIzlOJRvBLgInM',
    appId: '1:630175539288:ios:1b4aa4b831902c125eaa2d',
    messagingSenderId: '630175539288',
    projectId: 'barakahtime-cbfa8',
    storageBucket: 'barakahtime-cbfa8.firebasestorage.app',
    iosClientId: '630175539288-h16v371sst1fh3bnjo37joajoaplaqsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.barakahTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByjfjoy8PV0iHj-L2-quIzlOJRvBLgInM',
    appId: '1:630175539288:ios:1b4aa4b831902c125eaa2d',
    messagingSenderId: '630175539288',
    projectId: 'barakahtime-cbfa8',
    storageBucket: 'barakahtime-cbfa8.firebasestorage.app',
    iosClientId: '630175539288-h16v371sst1fh3bnjo37joajoaplaqsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.barakahTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAChF4hZA6jWlfHLQwWSXqM2BXO1U7Zw2U',
    appId: '1:630175539288:web:25dbc7619199ce2c5eaa2d',
    messagingSenderId: '630175539288',
    projectId: 'barakahtime-cbfa8',
    authDomain: 'barakahtime-cbfa8.firebaseapp.com',
    storageBucket: 'barakahtime-cbfa8.firebasestorage.app',
    measurementId: 'G-YGBGCDGVT6',
  );
}
